import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: [
    {
      path: '../public/fonts/Myfont-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Myfont2-Regular.otf',
      weight: '400',
      style: 'normal',
      
    },
  ],
  variable: '--font-myfont'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" style={{overflow: "hidden", height: "100%"}}>
<body className={`${geistSans.variable} ${geistMono.variable} ${myFont.variable}  antialiased`} style={{overflow: "hidden", height: "100%"}}>
        {children}
      </body>
    </html>
  );
}






